#ifndef COMMPACT_STATUS_H
#define COMMPACT_STATUS_H

#define CP_MK_ERROR(x) (0x00000000 | (x))

typedef enum {
  CP_SUCCESS = CP_MK_ERROR(0x0000),
  CP_CANT_OPEN_FILE = CP_MK_ERROR(0x8001),
  CP_ERROR = CP_MK_ERROR(0x8002),
  CP_WARN = CP_MK_ERROR(0x8004),
} commpact_status_t;

#endif // COMMPACT_STATUS_H
